version: '3.6'

networks:
  arkeo:
    driver: bridge
    attachable: true

services:
  arkeod:
    hostname: arkeod
    image: ghcr.io/arkeonetwork/arkeo:testnet
    pull_policy: always
    ports:
      - "1317:1317"
      - "9090:9090"
      - "26656:26656"
      - "26657:26657"
    networks:
      - arkeo
    volumes:
      - ".arkeo:/root/.arkeo:rw"
    environment:
      - NET="testnet"
      - ARKEOD_RPC_LADDR=tcp://0.0.0.0:26657
    entrypoint: /scripts/genesis.sh
  postgres:
    image: postgres:15.1-alpine
    container_name: arkeo-directory-pg
    restart: always
    environment:
      POSTGRES_DB: arkeo_directory
      POSTGRES_USER: arkeo
      POSTGRES_PASSWORD: arkeo123
    networks:
      - arkeo
    ports:
      - 5432:5432

  indexer:
    build:
      dockerfile: docker/dev/Dockerfile.indexer
    env_file:
      - docker/dev/docker.env
    depends_on:
      - postgres
    networks:
      - arkeo

  api:
    build:
      dockerfile: docker/dev/Dockerfile.api
    env_file:
      - docker/dev/docker.env
    depends_on:
      - postgres
    networks:
      - arkeo
    ports:
      - 7777:7777

  sentinel:
    image: ghcr.io/arkeonetwork/arkeo:testnet
    depends_on:
      - "arkeod"
    ports:
      - "3636:3636"
    networks:
      - arkeo
    environment:
      NET: "testnet"
      MONIKER: "local"
      WEBSITE: "n/a"
      DESCRIPTION: "n/a"
      LOCATION: "n/a"
      PORT: "3636"
      PROXY_HOST: "https://swapi.dev"
      SOURCE_CHAIN: "http://arkeod:1317"
      EVENT_STREAM_HOST: "arkeod:26657"
      FREE_RATE_LIMIT: 10
      FREE_RATE_LIMIT_DURATION: "1m"
      SUB_RATE_LIMIT: 10
      SUB_RATE_LIMIT_DURATION: "1m"
      AS_GO_RATE_LIMIT: 10
      AS_GO_RATE_LIMIT_DURATION: "1m"
      CLAIM_STORE_LOCATION: "/root/.arkeo/claims"
      TMHOME: "/root/.arkeo"
      GAIA_RPC_ARCHIVE_HOST: "http://176.34.207.130:26657"
    entrypoint: "/scripts/sentinel.sh"
    command: sentinel
    volumes:
      - ".sentinel:/root/.arkeo:rw"
      # - "./scripts:/scripts"
