version: '3.6'

networks:
  arkeo:
    driver: bridge
    attachable: true

services:
  postgres:
    image: postgres:15.1-alpine
    container_name: arkeo-directory-pg
    restart: always
    environment:
      POSTGRES_DB: arkeo_directory
      POSTGRES_USER: arkeo
      POSTGRES_PASSWORD: arkeo123
    networks:
      - arkeo
    ports:
      - 5432:5432

  arkeo-protocol:
    container_name: arkeo-protocol
    image: arkeo-protocol:latest
    environment:
      - ARKEOD_RPC_LADDR=tcp://0.0.0.0:26657
    networks:
      - arkeo
    ports:
      - 1317:1317
      - 9090:9090
      - 26656-26657:26656-26657

  indexer:
    build:
      dockerfile: docker/dev/Dockerfile.indexer
    env_file:
      - docker/dev/docker.env
    depends_on:
      - postgres
      - arkeo-protocol
    networks:
      - arkeo

  api:
    build:
      dockerfile: docker/dev/Dockerfile.api
    env_file:
      - docker/dev/docker.env
    depends_on:
      - postgres
    networks:
      - arkeo
    ports:
      - 7777:7777
