apiVersion: v1
kind: Service
metadata:
  name: arkeo-directory-service
  namespace: foundation
  labels:
    app: arkeo-directory-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: api
  selector:
    app: arkeo-directory-api
