apiVersion: v1
kind: ConfigMap
metadata:
  name: directory-config
  namespace: foundation
data:
  INDEXER_ID: "0" # TODO remove
  API_LISTEN: "0.0.0.0:80"
  NET: "testnet"
  CHAIN_ID: "arkeo"
  BECH32_PREF_ACC_ADDR: "arkeo"
  BECH32_PREF_ACC_PUB: "arkeopub"
  ARKEO_API: "http://testnet-seed.arkeo.shapeshift.com:1317"
  TENDERMINT_API: "http://testnet-seed.arkeo.shapeshift.com:26657"
  TENDERMINT_WS: "tcp://testnet-seed.arkeo.shapeshift.com:26657"
  # rest of db config see secrets
  DB_NAME: "directorydb"
  DB_POOL_MAX_CONNS: "2"
  DB_POOL_MIN_CONNS: "1"
  DB_SSL_MODE: "prefer"
